[general]
live_config_reload = true

[terminal]
shell = { program = "/usr/bin/zsh", args = ["-l"] }

[window]
title = "Alacritty"
dynamic_title = true
decorations = "None"
startup_mode = "SimpleFullscreen"
opacity = 0.95
padding = { x = 20, y = 20 }
dimensions = { columns = 90, lines = 27 }

[font]
size = 14.0
builtin_box_drawing = true

normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }

offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true
blink_interval = 750

[selection]
save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Plus", mods = "Control", action = "None" },
  { key = "Minus", mods = "Control", action = "None" },
  { key = "Equals", mods = "Control", action = "None" },

  { key = "C", mods = "Shift", action = "Copy" },
  { key = "V", mods = "Shift", action = "Paste" },

  { key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
  { key = "PageDown", mods = "Shift", action = "ScrollPageDown" },

  { key = "V", mods = "Control", action = "ToggleViMode" },
  { key = "F", mods = "Control|Shift", action = "ToggleFullscreen" },
  { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "W", mods = "Control|Shift", action = "Quit" }
]
